### ISSUE TITLE
is it possible make the tags undeletable?

### ISSUE THREAD

**Issue by Devofure** [Eddydpyl/AndroidTagGroup#5]
how to remove the cross?

**Comment by Eddydpyl** [comment]
A TagGroup has two modes of operating, one for just viewing existing tags another one for editing. The one for viewing is called the DISPLAY mode, and the one for editing APPEND mode. The mode can be set in the .xml file. If what you are asking is if it's possible to make tags undeletable while in APPEND mode, I don't think it is at the moment.
